routing:
  API:
    mobile:
      cities: "/mobile/cities"
      contexts: "/mobile/cities/:city_id/contexts"
      contexts_bis: "/mobile/contexts"
      users:  "/mobile/contexts/:context_id/users"
      adjustment_types: "/mobile/cities/:city_id/contexts/:context_id/users/:firstname_id/adjustment_types"
      translates: "/mobile/translates"
      adjustments: "/mobile/cities/:city_id/contexts/:context_id/users/:firstname_id/adjustment_types/:adjustment_type_id/adjustments"
      crews: "/mobile/contexts/users/:firstname_id/crews"
      daytimes: "/mobile/cities/:city_id/contexts/:context_id/daytimes"
      contexts_searchs: "/mobile/cities/:city_id/contexts/:context_id/users/:firstname_id/contexts_searchs"
    common:  
      boat_types: "/common/boat_types"
      sellers: "/common/contexts/:context_id/users/:user_id/boat_types/:boat_type_id/sellers"
      manufacturers: "/common/contexts/:context_id/users/:user_id/boat_types/:boat_type_id/manufacturers"
routing_backbonejs:
  API:
    mobile:
      contexts:
        routes:
          "/mobile/city/:city_id/users/:firstname_id/contexts" : "index"
          "/mobile/city/:city_id/users/:firstname_id/contexts/new" : "new"
          "/mobile/city/:city_id/users/:firstname_id/contexts/:id/edit" : "edit"
          "/mobile/city/:city_id/contexts/:id" : "destroy"
      adjustment_types:
        routes: 
          "/mobile/cities/:city_id/contexts/:context_id/users/:firstname_id/adjustment_types" : "index"
          "/mobile/cities/:city_id/contexts/:context_id/users/:firstname_id/adjustment_types/edit" : "edit"
      cities:
        routes:
          "/mobile/cities/:id/edit" : "edit"
          "/mobile/cities/:id" : "destroy"
