require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DaytimesController do

  # This should return the minimal set of attributes required to create a valid
  # Daytime. As you add validations to Daytime, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DaytimesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all daytimes as @daytimes" do
      daytime = Daytime.create! valid_attributes
      get :index, {}, valid_session
      assigns(:daytimes).should eq([daytime])
    end
  end

  describe "GET show" do
    it "assigns the requested daytime as @daytime" do
      daytime = Daytime.create! valid_attributes
      get :show, {:id => daytime.to_param}, valid_session
      assigns(:daytime).should eq(daytime)
    end
  end

  describe "GET new" do
    it "assigns a new daytime as @daytime" do
      get :new, {}, valid_session
      assigns(:daytime).should be_a_new(Daytime)
    end
  end

  describe "GET edit" do
    it "assigns the requested daytime as @daytime" do
      daytime = Daytime.create! valid_attributes
      get :edit, {:id => daytime.to_param}, valid_session
      assigns(:daytime).should eq(daytime)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Daytime" do
        expect {
          post :create, {:daytime => valid_attributes}, valid_session
        }.to change(Daytime, :count).by(1)
      end

      it "assigns a newly created daytime as @daytime" do
        post :create, {:daytime => valid_attributes}, valid_session
        assigns(:daytime).should be_a(Daytime)
        assigns(:daytime).should be_persisted
      end

      it "redirects to the created daytime" do
        post :create, {:daytime => valid_attributes}, valid_session
        response.should redirect_to(Daytime.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved daytime as @daytime" do
        # Trigger the behavior that occurs when invalid params are submitted
        Daytime.any_instance.stub(:save).and_return(false)
        post :create, {:daytime => {  }}, valid_session
        assigns(:daytime).should be_a_new(Daytime)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Daytime.any_instance.stub(:save).and_return(false)
        post :create, {:daytime => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested daytime" do
        daytime = Daytime.create! valid_attributes
        # Assuming there are no other daytimes in the database, this
        # specifies that the Daytime created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Daytime.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => daytime.to_param, :daytime => { "these" => "params" }}, valid_session
      end

      it "assigns the requested daytime as @daytime" do
        daytime = Daytime.create! valid_attributes
        put :update, {:id => daytime.to_param, :daytime => valid_attributes}, valid_session
        assigns(:daytime).should eq(daytime)
      end

      it "redirects to the daytime" do
        daytime = Daytime.create! valid_attributes
        put :update, {:id => daytime.to_param, :daytime => valid_attributes}, valid_session
        response.should redirect_to(daytime)
      end
    end

    describe "with invalid params" do
      it "assigns the daytime as @daytime" do
        daytime = Daytime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Daytime.any_instance.stub(:save).and_return(false)
        put :update, {:id => daytime.to_param, :daytime => {  }}, valid_session
        assigns(:daytime).should eq(daytime)
      end

      it "re-renders the 'edit' template" do
        daytime = Daytime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Daytime.any_instance.stub(:save).and_return(false)
        put :update, {:id => daytime.to_param, :daytime => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested daytime" do
      daytime = Daytime.create! valid_attributes
      expect {
        delete :destroy, {:id => daytime.to_param}, valid_session
      }.to change(Daytime, :count).by(-1)
    end

    it "redirects to the daytimes list" do
      daytime = Daytime.create! valid_attributes
      delete :destroy, {:id => daytime.to_param}, valid_session
      response.should redirect_to(daytimes_url)
    end
  end

end
